name: Track Merges into Beta (Linked PR Titles)

on:
  pull_request:
    types:
      - closed
    branches:
      - beta
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  track_prs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get merged PRs into beta
        id: get_prs
        run: |
          RAW_PRS=$(gh pr list --base beta --state merged --json number,title,mergedAt -L 100 -R ${{ github.repository }})
          TODAY=$(date +'%Y-%m-%d')
          FORMATTED_PRS=$(echo "$RAW_PRS" | jq -r --arg TODAY "$TODAY" '
            m
