name: Track Merges into Beta (Linked PR Titles)

on:
  pull_request:
    types:
      - closed
    branches:
      - beta
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  track_prs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify .git and workspace
        run: |
          echo "Workspace: $(pwd)"
          ls -la
          if [ -d ".git" ]; then echo ".git found"; else echo ".git not found"; fi

      - name: Get merged PRs into beta and format as Markdown links
        id: get_prs
        run: |
          echo "Getting merged PRs..."
          RAW_PRS=$(gh pr list --base beta --state merged --json title,url -L 100 -R ${{ github.repository }})
          FORMATTED_PRS=$(echo "$RAW_PRS" | jq -r '.[] | "- [\(.title)](\(.url))"')
          
          if [ -z "$FORMATTED_PRS" ]; then
            echo "No merged PRs found."
            echo "PRS=" >> $GITHUB_ENV
          else
            echo "Merged PRs found:"
            echo "$FORMATTED_PRS"
            echo "PRS<<EOF" >> $GITHUB_ENV
            echo "$FORMATTED_PRS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Load QA member usernames
        id: load_qa
        run: |
          FILE=".github/workflows/qa_members.txt"
          if [ ! -f "$FILE" ]; then
            echo "QA member list not found: $FILE"
            echo "MENTIONS=" >> $GITHUB_ENV
          else
            MENTIONS=$(grep -v '^#' "$FILE" | sed '/^$/d' | sed 's/^/@/' | paste -sd ' ' -)
            echo "MENTIONS=$MENTIONS" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue for QA
        if: env.PRS != ''
        run: |
          ISSUE_TITLE="PRs Merged into Beta"
          ISSUE_BODY=$(printf "The following PRs have been merged into **beta**:\n\n%s\n\nPlease begin QA testing on the listed PRs.\n\nCC: %s" "${PRS}" "${MENTIONS}")
          
          echo "Creating issue with body:"
          echo "-----------------------------"
          echo "$ISSUE_BODY"
          echo "-----------------------------"

          printf "%s" "${ISSUE_BODY}" | gh issue create --title "$ISSUE_TITLE" --body-file - -R ${{ github.repository }}
