name: Track Merges into beta (Linked PR Titles)

on:
  pull_request:
    types:
      - closed
    branches:
      - beta
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  track_prs:
    # Only run if the PR was actually merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Verify the workspace and directory
      - name: Verify Workspace and Git Directory
        run: |
          echo "--- Verifying Checkout ---"
          echo "Current directory: $(pwd)"
          ls -la ${{ github.workspace }}
          if [ -d "${{ github.workspace }}/.git" ]; then echo ".git directory FOUND."; else echo ".git directory NOT FOUND."; fi
          echo "--- End Verification ---"

      - name: Get merged PRs into beta and format as Markdown links
        id: get_prs
        run: |
          echo "Attempting gh pr list command..."
          # Fetch both title and URL again to create links
          RAW_PRS=$(gh pr list --base beta --state merged --json title,url -L 100 -R ${{ github.repository }})

          # Use jq to format each PR as a Markdown link: [title](url)
          FORMATTED_PRS=$(echo "$RAW_PRS" | jq -r '.[] | "[\(.title)](\(.url))"')

          # Check if any PRs were found
          if [ -z "$FORMATTED_PRS" ]; then
            echo "No merged PRs found to report."
            FORMATTED_PRS=""
          else
            echo "Formatted PR Links:"
            echo "$FORMATTED_PRS"
          fi

          # Store the formatted markdown links in the GITHUB_ENV
          echo "PRS<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_PRS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create an Issue with the list of PR Links
        if: env.PRS != ''
        run: |
          ISSUE_TITLE="PRs Merged into beta"
          ISSUE_BODY=$(printf "Merged PRs:\n\n%s" "${PRS}")
          echo "Creating issue with title: $ISSUE_TITLE"
          printf "%s" "${ISSUE_BODY}" | gh issue create --title "$ISSUE_TITLE" --body-file - -R ${{ github.repository }}
          echo "Created issue: $ISSUE_TITLE"

      - name: Notify QA Team from qa_members.txt
        if: steps.create_issue.outputs.issue_url != ''
        run: |
          ISSUE_URL="${{ steps.create_issue.outputs.issue_url }}"
          ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oE '[0-9]+')
          
          # Read the list of QA members from qa_members.txt
          QA_MEMBERS=$(cat .github/workflows/qa_members.txt)

          # Add a comment mentioning all QA members
          COMMENT_BODY="@${QA_MEMBERS} This PR merge to beta requires QA testing. Please review the changes listed in this issue and prioritize testing for the upcoming release."
          
          # Add the comment
          gh issue comment "$ISSUE_NUMBER" --body "$COMMENT_BODY" -R ${{ github.repository }}
