name: Track Merges into Beta (Linked PR Titles) # Updated name for clarity

on:
  pull_request:
    types:
      - closed
    branches:
      - beta

jobs:
  track_prs:
    # Only run if the PR was actually merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: You can remove this verification step if you are confident checkout works
      - name: Verify Workspace and Git Directory
        run: |
          echo "--- Verifying Checkout ---"
          echo "Current directory: $(pwd)"
          ls -la ${{ github.workspace }}
          if [ -d "${{ github.workspace }}/.git" ]; then echo ".git directory FOUND."; else echo ".git directory NOT FOUND."; fi
          echo "--- End Verification ---"

      - name: Get merged PRs into beta and format as Markdown links
        id: get_prs
        run: |
          echo "Attempting gh pr list command..."
          # Fetch both title and url again to create links
          RAW_PRS=$(gh pr list --base beta --state merged --json title,url -L 100 -R ${{ github.repository }})

          # Use jq to format each PR as a Markdown link: [title](url)
          # Note the quotes within the jq string to create the markdown
          FORMATTED_PRS=$(echo "$RAW_PRS" | jq -r '.[] | "[\(.title)](\(.url))"')

          # Check if any PRs were found
          if [ -z "$FORMATTED_PRS" ]; then
            echo "No merged PRs found to report."
            FORMATTED_PRS=""
          else
            echo "Formatted PR Links:"
            echo "$FORMATTED_PRS" # Output will be lines of [title](url)
          fi

          # Store the formatted markdown links in the GITHUB_ENV
          echo "PRS<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_PRS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create an Issue with the list of PR Links
        # Only run this step if the PRS variable is not empty
        if: env.PRS != ''
        run: |
          ISSUE_TITLE="PRs Merged into Beta"
          # Construct the body string ensuring newlines are preserved correctly BEFORE piping
          # Using printf for the body construction part
          ISSUE_BODY=$(printf "Merged PRs:\n\n%s" "${PRS}")

          echo "Creating issue with title: $ISSUE_TITLE"
          # Log the body exactly as it will be passed to gh issue create
          echo "--- Issue Body Start ---"
          echo "${ISSUE_BODY}"
          echo "--- Issue Body End ---"

          # Pipe the body content via stdin to gh issue create using --body-file -
          # This handles newlines and special characters more reliably
          printf "%s" "${ISSUE_BODY}" | gh issue create --title "$ISSUE_TITLE" --body-file - -R ${{ github.repository }}
